### ISSUE TITLE
Accessibility: Authorization Screen and Google Docs Interface

### ISSUE THREAD

**Issue by csonnek** [Automattic/google-docs-add-on#31] opened 2017-03-10 19:12 UTC
Moving here from our internal blog.

Had a user contact us (who is blind) in 3098158-t who is having trouble authorizing their Jetpack site because it’s not apparent that there’s a drop down:

![authorize_wordpress_com_for_google_docs](https://cloud.githubusercontent.com/assets/2814452/23809365/01bf32fe-0593-11e7-88b8-a4d40e4e1079.png)

While we’re visually prompted that it is a drop down, to her it’s not apparent as the down arrow isn’t accessible via keyboard. Even walking her through the steps in great detail using only my keyboard, she’s not able to select her Jetpack site since it’s not the first site in her list.

Additionally, in the list of sites in Google docs – there’s no way to remove a site once it’s been added unless you use a mouse hover:

![accessible](https://cloud.githubusercontent.com/assets/2814452/23809382/149bc2fc-0593-11e7-93f1-3f78d47aec2c.gif)

Testing for screen reader devices would be the first step in relieving these pain points for visually impaired users.

**Comment by johngodley** [comment] 2017-03-13 09:16
> While we’re visually prompted that it is a drop down, to her it’s not apparent as the down arrow isn’t accessible via keyboard. Even walking her through the steps in great detail using only my keyboard, she’s not able to select her Jetpack site since it’s not the first site in her list.

Just noting that this problem isn't caused by this plugin itself, but is part of the general WordPress.com / Jetpack authentication process. It definitely needs improving, and is worth bringing up elsewhere.

**Comment by johngodley** [comment] 2017-03-13 09:44
For the second part I think a link (with confirmation) would help.

Another problem with the X appearing on hover is encountered if the site name is long:

<img width="323" alt="hover" src="https://cloud.githubusercontent.com/assets/1277682/23849014/96d7b3da-07d1-11e7-8429-8da8eba0530b.png">

**Comment by georgeh** [comment] 2017-04-12 20:49
The accessibility of the "remove site" button has been fixed, and the drop-down is something that is going to need to be addressed by the API team. We should be good here

**Closed by georgeh** 2017-04-12 20:49 UTC
Labels: enhancement
